#
# Module manifest for module 'GoFilePath'
# Generated by: Eric
# Generated on: 1/7/2020
#

@{
	RootModule            = 'GoFilePath.psm1'
	ModuleVersion         = '0.0.1'
	GUID                  = '9F53432A-5A19-47DB-B6A3-B2586B556A87'
	Author                = 'Eric'
	CompanyName           = 'Eric'
	Copyright             = '(c) 2019-2020 Eric. All rights reserved.'
	Description           = 'Functionality for testing go API on Windows'
	PowerShellVersion     = '2.0'   # Minimum version of the PowerShell engine required
	# CompatiblePSEditions  = @(      # Supported PSEditions
	#	'Desktop'
	#	'Core'
	# )
	# PowerShellHostName = ''       # Name of the PowerShell host required
	# PowerShellHostVersion = ''    # Minimum version of the PowerShell host required
	# DotNetFrameworkVersion = ''   # Minimum version of Microsoft .NET Framework required (PowerShell Desktop)
	CLRVersion            = '2.0'   # Minimum version of the CLR required (PowerShell Desktop)
	ProcessorArchitecture = 'None'  # Processor architecture (None, X86, Amd64) required
	RequiredModules = @(            # Modules that must be imported prior to this module
		@{
			ModuleName = 'Hyper-V'
			ModuleVersion = '2.0.0'
			Guid = 'af4bddd0-8583-4ff2-84b2-a33f5c8de8a7'
		}
	)
	# RequiredAssemblies = @()      # Assemblies that must be loaded prior to this module

	ScriptsToProcess      = @()     # Script files (.ps1) run in the caller's environment prior to importing this module.
	TypesToProcess        = @()     # Type files (.ps1xml) to be loaded when importing this module
	FormatsToProcess      = @()     # Format files (.ps1xml) to be loaded when importing this module
	NestedModules         = @()     # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	FunctionsToExport     = @(      # Functions to export
		'New-GoPaths'
		'Remove-GoPaths'
		'Get-GoFilePath'
		'Set-GoFilePath'
	)
	CmdletsToExport       = @()     # Cmdlets to export
	VariablesToExport     = '*'     # Variables to export
	AliasesToExport       = @(      # Aliases to export from this module
		'gof'
	)
	DscResourcesToExport  = @()     # DSC resources to export from this module
	ModuleList            = @()     # List of all modules packaged with this module
	FileList              = @()     # List of all files packaged with this module

	PrivateData           = @{

		PSData = @{
			ProjectUri = 'https://github.com/ericwj/GoWindows'
			LicenseUri = 'https://github.com/ericwj/GoWindows/raw/master/LICENSE.txt'
			RequireLicenseAcceptance = $false
			Prerelease = 'beta'
			Tags = @(
				# Tags for PowerShell Gallery
				'PSEdition_Desktop', 'PSEdition_Core', 'Windows',
				# Tags describing the functionality of this module
				'go', 'gofilepath', 'gopathfilepath', 'gof'
			)
		}

	} # End of PrivateData hashtable

	HelpInfoURI = ''				# HelpInfo URI
	DefaultCommandPrefix = ''		# Default prefix for exported commands. Override the default prefix using Import-Module -Prefix.
}

